### ISSUE TITLE
Update AI model and make AI determine effects

### ISSUE THREAD

**Issue by wwsean08** [clarkio/ttv-chat-light#43]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)

- [ ] bug report -> please search issues before submitting
- [X] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

This came out of the stream tonight that we need to update the AI to handle more effects (like tips, hosts, raids etc).

Also allow the chat client to send the AI a message like `trigger pulse green purple` to cause it to pulse green/purple or other similar lifx supported commands

**Comment by clarkio** [comment]
Thanks for opening this issue while the stream was going @wwsean08

**Comment by clarkio** [comment]
Completed in #45. Closing...
