### ISSUE TITLE
Custom Epic User Intro Sounds

### ISSUE THREAD

**Issue by ElectricHavoc** [clarkio/ttv-chat-light#65]
### Custom Intro Sounds

- Specific Media Folder
- FileName = Twitch Name
- Detect first text in chat
- Plays matching sound
- Some limit to sound length (slightly longer than !shock, e.g. 2 sec)
- User has to submit via PR

Stretch goals
- Command to trigger after
  - Only by user !myintro
- Outros also
  - {name}_intro.wav and {name}_outro.wav
  - !myintro !myoutro
- Admin/Mod cmds
  - !user_{name}_{intro/outro}

**Comment by clarkio** [comment]
Didn't get a chance to talk through it more during the game stream but here's what I've begun doing to implement functionality for viewer sounds...

- Detect when someone joins the chat
- Check if they have a join sound defined in the effects configuration
- Play the sound

Effects Configuration example: https://github.com/clarkio/ttv-chat-light/blob/master/src/server/effects.json#L72

Code to try and activate a "join" sound: https://github.com/clarkio/ttv-chat-light/blob/master/src/server/twitch-chat.ts#L94

Let me know what you all think. This can also be done for when someone leaves. 

The one potential issue I could see with this is if someone just wants to peek into the stream but not really be noticed. I suppose a solution to that is to not have a join/depart sound configured for yourself (assuming people will choose to make a PR to add themselves [used themichaeljolley and roberttables as guinea pigs so far]).

**Comment by clarkio** [comment]
Finished in https://github.com/clarkio/ttv-chat-light/commit/afec9722fa060b301e83c8076a237d7d464fb0bb

Closing
