### ISSUE TITLE
Add all contributors to readme

### ISSUE THREAD

**Issue by clarkio** [clarkio/ttv-chat-light#72]
@all-contributors please add @jakegny for code
@all-contributors please add @MichaelCduBois for code
@all-contributors please add @MichaelJolley for code
@all-contributors please add @sorskoot for code
@all-contributors please add @ElectricHavoc for code
@all-contributors please add @lannonbr for code
@all-contributors please add @CodemanCodes for code
@all-contributors please add @jaredpsimpson for code
@all-contributors please add @eeevans for code
@all-contributors please add @nmarch213 for code

**Comment by clarkio** [comment]
@all-contributors please add @jakegny for code
@all-contributors please add @MichaelCduBois for code
@all-contributors please add @MichaelJolley for code
@all-contributors please add @sorskoot for code
@all-contributors please add @ElectricHavoc for code
@all-contributors please add @lannonbr for code
@all-contributors please add @CodemanCodes for code
@all-contributors please add @jaredpsimpson for code
@all-contributors please add @eeevans for code
@all-contributors please add @nmarch213 for code

**Comment by clarkio** [comment]
@all-contributors please add @jakegny for code

**Comment by clarkio** [comment]
@all-contributors please add @MichaelCduBois for code

@all-contributors please add @MichaelJolley for code

@all-contributors please add @sorskoot for code

@all-contributors please add @ElectricHavoc for code

@all-contributors please add @lannonbr for code

@all-contributors please add @Code
manCode
s for code

@all-contributors please add @jaredpsimpson for code

@all-contributors please add @eeevans for code

@all-contributors please add @nmarch213 for code

**Comment by clarkio** [comment]
@all-contributors please add @nmarch213 for code

**Comment by clarkio** [comment]
@all-contributors please add @eeevans for code

**Comment by clarkio** [comment]
@all-contributors please add @jaredpsimpson for code

**Comment by clarkio** [comment]
@all-contributors please add @CodemanCodes for code

**Comment by MichaelJolley** [comment]
@all-contributors please add @jakegny for code

**Comment by MichaelJolley** [comment]
@all-contributors please add @MichaelCduBois for code

**Comment by MichaelJolley** [comment]
@all-contributors please add @sorskoot for code

**Comment by clarkio** [comment]
@all-contributors please add @lannonbr for code

**Comment by clarkio** [comment]
All contributors listed in this issue have now been added.
