### ISSUE TITLE
!bulb Black hides overlay details

### ISSUE THREAD

**Issue by PatPat1567** [clarkio/ttv-chat-light#77]
### This issue is for a: (mark with an `x`)

- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)

### Minimal steps to reproduce
>!bulb black

### Any log messages given by the failure
> N/A

### Expected/desired behavior
>When overlay color changes to black, you lose the recent follower box and the branding elements. I would expect those would be colored white or another color.

### OS and Version?
> N/A

### Versions
> Latest version

### Mention any other details that might be useful
https://clips.twitch.tv/BrightEsteemedClintPastaThat

**Comment by clarkio** [comment]
@all-contributors please add @PatPat1567 for bugs

**Comment by clarkio** [comment]
Thanks for pointing this out. We've now adjusted the css for .black class to just darken to overlay and not completely hide it. I think that is a good compromise.

Added in the following:
https://github.com/clarkio/ttv-chat-light/commit/87397d1538320c21bb8589dfd85644ad4d8d2d1c
