### ISSUE TITLE
Audio tracks are parsed in parallel for duration

### ISSUE THREAD

**Issue by Borewit** [clarkio/ttv-chat-light#97]
If a lot files are parsed in parallel, this may cause a seriously slow down the system.

In the code the following comment can be found: (_Array.forEach is blocking aka synchronous_)

https://github.com/clarkio/ttv-chat-light/blob/bbfecb5725f5be39a95805c3c38215c7db26c1cf/src/server/sound-fx.ts#L101-L102

This is not the case, Array.forEach is [not blocking](https://codeburst.io/javascript-async-await-with-foreach-b6ba62bbf404).

A _for_ loop is blocking in combination with `await`. However a `for` loop would not directly make a difference neither because the expensive task executed in that loop is `mp3Duration` , which is an asynchronous (non blocking), not returning a promise.

Using `await` in combination with a `for` loop is a way to make it synchronous: PR #98.

**Comment by clarkio** [comment]
We're running this locally on a machine, it only happens once at start up of the bot and we're only dealing with about 100 files so this feels a bit of a preemptive optimization that is not necessary for the purposes of this project.

I tested things out with the original code/library and am happy with the performance of it. Thank you for raising this concern.
